---

wan_mode: cv-pathfinder
wan_stun_dtls_disable: true
cv_pathfinder_regions:
  - name: Region1
    id: 1
    sites:
      - name: DC1
        id: 101
        location: San Jose, CA
      - name: DC2
        location: New Orleans, LA
        id: 102
      - name: CAMPUS1
        id: 111
        location: New York, New York
      - name: PATHFINDERS
        id: 255
        location: Singapore, Singapore
 

# cv_pathfinder_regions:
#   - name: Global
#     id: 1
#     sites:
#       - name: REGION1_SITE1
#         id: 101
#       - name: REGION1_SITE2
#         id: 102
#       - name: REGION1_HUB
#         id: 111
#       - name: REGION2_SITE1
#         id: 103
#       - name: REGION2_SITE2
#         id: 104
#       - name: REGION2_HUB
#         id: 112


bgp_peer_groups:
  wan_overlay_peers:
    bfd_timers:
      interval: 15000
      min_rx: 15000
      multiplier: 3   
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 10.0.0.0/9
    

wan_route_servers:
  - hostname: pf1
    vtep_ip: 10.255.0.1
    path_groups:
      - name: INET
        interfaces:
          - name: Ethernet1/1
            public_ip: 172.16.51.2
     
    

  - hostname: pf2
    vtep_ip: 10.255.0.2
    path_groups:
      - name: INET
        interfaces:
          - name: Ethernet1/1
            public_ip: 172.16.52.2
    

wan_ipsec_profiles:
  control_plane:
    shared_key: 0110100A480E0A0E231D1E
  data_plane:
    shared_key: 0110100A480E0A0E231D1E

wan_path_groups:
  - name: INET
    ipsec:
      static_peers: true
      dynamic_peers: true
    dps_keepalive:
      interval: 50
      failure_threshold: 3
    id: 101
  

wan_carriers:
  - name: INET
    path_group: INET
    trusted: true
 
wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
      wan_vni: 1
    - name: customer1
      policy: DTN-AVT-POLICY
      wan_vni: 2  
   


  
  policies:
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
    # - name: CUSTOMER1-AVT-POLICY
    #   default_virtual_topology:
    #     path_groups:
    #       - names: [rmpls1,rmpls2,rmpls3,rmpls4,gmpls1,gmpls2]
    #         preference: preferred
    # - name: CUSTOMER2-AVT-POLICY
    #   default_virtual_topology:
    #     path_groups:
    #       - names: [rmpls1,rmpls2,rmpls3,rmpls4,gmpls1,gmpls2]
    #         preference: preferred
    - name: DTN-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
      application_virtual_topologies:
        - application_profile: VOICE 
          # if you enable lowest hop count it will disable FRR
          lowest_hop_count: false
          path_groups:
            - names: [INET]
              preference: preferred
          constraints: 
            latency: 120
            jitter: 20
            loss_rate: 0.3
          id: 2 


# Application traffic recognition configuration.
application_classification:
  field_sets:
    l4_ports: 
    - name: RTP_PORT
      port_values: [1-65000]
  # Group of applications.
  application_profiles:
    - name: VOICE
     
     # Can be custom defined APP, or builtin Cosmos app
      applications:
        - name: voice-udpport
        - name: erspan


      
      # service: "audio-video"
      # application_transports:
      #   - "rtp"
 
  applications:
    ipv4_applications:
      - name: voice-udpport
        udp_dest_port_set_name: RTP_PORT
        protocols: 
          - "udp"
