
mgmt_interface: Management1

wan_router: # dynamic_key: node_type
  defaults:
    cv_pathfinder_region: Region1
    cv_pathfinder_site: CAMPUS1
    loopback_ipv4_pool: 10.1.2.0/26
    vtep_loopback_ipv4_pool: 10.1.2.64/26
    uplink_ipv4_pool: 10.1.2.128/26
    uplink_interface_speed: 10g
    uplink_type: p2p-vrfs # uplink to local switch
    uplink_interfaces: [ Ethernet2 ]
    uplink_switches: [ campus1-leaf1 ]
    bgp_as: 65000
    filter:
      always_include_vrfs_in_tenants:
        - campus1
    wan_ha:
      enabled: true
      ha_interfaces: [Ethernet3] 
      ha_ipv4_pool: 10.10.12.0/24
      ipsec: false
  node_groups:
    - group: WAN_CAMPUS1
      nodes:
        - name: campus1-wan1
          id: 1
          mgmt_ip: 172.28.143.217/20
          uplink_switch_interfaces: [ Ethernet47 ]
          l3_interfaces:
            - name: Ethernet1
              structured_config:
                mtu: 9000
              ip_address: 172.16.123.2/30
              wan_carrier: INET
              wan_circuit_id: CAMPUS1-WAN1-INET
              peer_ip: 172.16.123.1
              static_routes:
                - prefix: 172.16.0.0/16
        - name: campus1-wan2
          id: 2
          mgmt_ip: 172.28.143.240/20
          uplink_switch_interfaces: [ Ethernet48 ]
          l3_interfaces:
            - name: Ethernet1
              structured_config:
                mtu: 9000
              ip_address: 172.16.124.2/30
              wan_carrier: INET
              wan_circuit_id: CAMPUS1-WAN2-INET
              peer_ip: 172.16.124.1
              static_routes:
                - prefix: 172.16.0.0/16

### LEAFS ###

l3leaf: # dynamic_key: node_type
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 10.1.2.0/26
    vtep_loopback_ipv4_pool: 10.1.2.64/26
    uplink_ipv4_pool: 10.1.2.128/26
    # mlag_interfaces: [Ethernet5, Ethernet6]
    # mlag_peer_ipv4_pool: 10.103.3.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  nodes:
    - name: campus1-leaf1
      id: 3
      mgmt_interface: Management1
      mgmt_ip: 172.28.134.110/20
      bgp_as: 65012


# custom_structured_configuration_eos_cli: |
# platform tfa personality arfa

