---
# WAN Pathfinder Nodes

mgmt_interface: Management1

wan_rr: # dynamic_key: node_type
  defaults:
    data_plane_cpu_allocation_max: 1
    loopback_ipv4_pool: 10.10.0.0/30
    vtep_loopback_ipv4_pool: 10.255.0.0/30
    bgp_as: 65000
  nodes:
    - name: pf1
      cv_pathfinder_region: Region1
      cv_pathfinder_site: PATHFINDERS
      id: 1
      mgmt_ip: 172.28.143.238/17
      l3_interfaces:
        - name: Ethernet1
          ip_address: 172.16.51.2/30
          wan_carrier: INET
          wan_circuit_id: PF-INET-1
          peer_ip: 172.16.51.1
          static_routes:
            - prefix: 172.16.0.0/16
       
    - name: pf2
      id: 2
      cv_pathfinder_region: Region1
      cv_pathfinder_site: PATHFINDERS
      mgmt_ip: 172.28.143.226/17
      l3_interfaces:
        - name: Ethernet1
          ip_address: 172.16.52.2/30
          wan_carrier: INET
          wan_circuit_id: PF-INET-1
          peer_ip: 172.16.52.1
          static_routes:
            - prefix: 172.16.0.0/16
       


